### ISSUE TITLE
Hardly see Math formulas in dark mode.

### ISSUE THREAD

**Issue by quyentruong** [bitcookies/winrar-keygen#11]
https://github.com/bitcookies/winrar-keygen/blob/master/README.HOW_DOES_IT_WORK.md

![image](https://user-images.githubusercontent.com/22864140/152696961-b6eff990-94a1-4d06-98c2-bd58eca2b763.png)

I don't know if it's possible to change the font color.

**Comment by bitcookies** [comment]
Yes. It is indeed difficult to see. 😧

> GitHub does not allow for CSS to affect files through CSS for security reasons (as if you could inject CSS into a ReadMe, you could easily launch a phishing attack). This includes both stylesheets referenced through and inline styles used with. `README.md` `<link rel>` `<style>`
>
>https://stackoverflow.com/questions/51956361/custom-css-file-for-readme-md-in-a-github-repo

But there are still two solutions

#### 1. Add Background Color
Like this. But white background can be very harsh in dark themes.

![0](https://user-images.githubusercontent.com/18363796/152738900-c176a451-b320-4baa-91c6-aa6902843934.png)

#### 2. SVG Recolor
The second way is, recolor the svg to find a suitable color.

Github currently has **only three** different colors of dark themes, we just need to find a suitable color. Like this

![2](https://user-images.githubusercontent.com/18363796/152739403-be02ed94-2b54-44ff-baa3-9a24179702c6.png)

I'm worried about which color to use, do you have any good ideas? 😶

**Comment by quyentruong** [comment]
I found an example to show which image in light mode or dark mode
https://github.com/stefanjudis/github-light-dark-image-example

The formulas look fine in the light mode. Now you just need to add other formulas in dark mode. I think white text with black background should be ok.

**Comment by bitcookies** [comment]
Cool~ 😁
I will update the `README.md` and `README.HOW_DOES_IT_WORK.md` in the next few days.

**Comment by bitcookies** [comment]
🌙 The following files have been adapted to the **Github Dark Theme**

- README.md
- README.zh-CN.md
- README.HOW_DOES_IT_WORK.md
- README.HOW_DOES_IT_WORK.zh-CN.md
