### ISSUE TITLE
Registration Failed

### ISSUE THREAD

**Issue by nitu2003** [bitcookies/winrar-keygen#2]
```
RAR registration data
Github
Github.com
UID=3a3d02329a32b63da7d8
6412212250a7d8753c5e7037d83011171578c57042fa30c506caae
9954e4853d415ec594e460a7213ad70c9139c941613a53b6798ea8
aa19873a1f107ba38957c31029722ba44f4c88667180de0dd18d35
b59927bfb6c3db0f916a59b707c657bc9360faa4200e4ee2cbd7e2
7ca2797b748eb2edce71ac60b2e8cca23563003c752ba44f4c8866
7180de0dfb4545465f32e0b12aa3bcaf0e9c21b4425f627c609b18
5eede7ed46566b10bf033daa6384062b259194b1acbd3027113380
```

WinRAR version: 6.0.2

**Comment by bitcookies** [comment]
The above registration information is all correct. My WinRAR 6.0.2 version registered and tested successfully.

You need to save the above registration information in **text format** as `rarreg.key`, and drag it to the winrar window. 😀

**Comment by nitu2003** [comment]
Thx.
It didn't work and I didn't know why.
Then it works and I don't know why.

**Comment by nitu2003** [comment]
Oh, I found the key file generated by powershell with command is writen in UTF-16 LE and the one I created myself is in UTF-8. I think it is the cause.

**Comment by bitcookies** [comment]
Yes, this may be a reason. 
There is another reason for generating invalid keys. 🙄

If `text1` and `text2` contain **non-English characters**, although a key can be generated, the key is invalid.

```console
winrar-keygen.exe <text1> <text2>
```

Thanks for the feedback, the README will be updated later. 😁

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
@bitcookies The text encoding of the file should be ANSI, a.k.a Windows-1252 encoding, **not** UTF-8.
If I create a file containing printable characters above the common ASCII range, 0x80 to 0xFF in ANSI encoding, the file is still valid.

**Comment by bitcookies** [comment]
> @bitcookies The text encoding of the file should be ANSI, a.k.a Windows-1252 encoding, **not** UTF-8. If I create a file containing printable characters above the common ASCII range, 0x80 to 0xFF in ANSI encoding, the file is still valid.

@Sonic-The-Hedgehog-LNK1123 Indeed. `Username` and `License type` are ANSI-encoded string, without null-terminator.

The readme will be modified later. Thanks and have a great weekend! 😆
