### ISSUE TITLE
Workflows are not available.

### ISSUE THREAD

**Issue by PanoptesDreams** [bitcookies/winrar-keygen#26]
By simply following the tutorial you may hit a roadblock because the workflows are not visible.

This is because they are disabled by default on forked repos.

Could you add a note in the readme to warn noobs like me to press 'that button' to enable them.
I found the button but pushed it before documenting the process.

**Comment by bitcookies** [comment]
Thanks for the suggestion, will improve the description of the README later!

**Comment by bitcookies** [comment]
README has been updated and is now friendly enough to follow in step-by-step order.

Have Fun 😁
