### ISSUE TITLE
(win10) Can't run keygenx64.exe

### ISSUE THREAD

**Issue by hoagN1** [bitcookies/winrar-keygen#4]
i do disabled window defense but it didn't seem to work. it just flash open a console like cmd window and close itself immediately

**Comment by bitcookies** [comment]
> i do disabled window defense but it didn't seem to work. it just flash open a console like cmd window and close itself immediately

This is essentially a command line and requires a terminal to run. For example CMD, powershell or terminal.

A total of two parameters are required. Use the following command to generate the key:

```console
consloswinrar-keygen.exe <Parameter 1> <Parameter 2>
```
Considering the copyright of RARLAB, I am considering whether to release a GUI version. But the main purpose of this repo is still to explain the principle of key generation. 😀

**Comment by hoagN1** [comment]
C:\WINDOWS\system32>winrar-keygen-x64.exe "Github" "Github.com" 
'winrar-keygen.exe' is not recognized as an internal or external command,
operable program or batch file.
how can i fix this. 

thankyou for taking your time answering my questions

**Comment by bitcookies** [comment]
> C:\WINDOWS\system32>winrar-keygen-x64.exe "Github" "Github.com"
> 'winrar-keygen.exe' is not recognized as an internal or external command,
> operable program or batch file.
> how can i fix this.
> 
> thankyou for taking your time answering my questions

Oh, the problem is that the path is wrong.

For example, `winrar-keygen-x64.exe` is saved on your Windows Desktop. 
The file location is `C:\Users\yourname\Desktop\winrar-keygen-x64.exe`
Then the command is `C:\Users\yourname\Desktop\winrar-keygen-x64.exe Github Github.com`

Open CMD, and then drag `winrar-keygen-x64.exe` to CMD window will generate the corresponding directory. 😉

**Comment by hoagN1** [comment]
:((((( now i can't drag the "rarreg.key" in IDM i try reinstall it run normally and on admin but no luck. so i "open file location" and drag the "rarreg.key" straight into it but still no luck. my IDM are on 6.38

**Comment by bitcookies** [comment]
> :((((( now i can't drag the "rarreg.key" in IDM i try reinstall it and run it normally and on admin but no luck. so i "open file location" and drag the "rarreg.key" straight into it but still no luck. my IDM are on 6.38

emm? What is IDM? 🤨

If you successfully generated and saved `rarreg.key`, just open winrar and drag rarreg.key to the winrar window, and you will be prompted whether to import information.

If you are unable to drag, you can try to put the `rarreg.key` in the following directory.

```console
C:\Users\yourname\AppData\Roaming\WinRAR\rarreg.key
```

I haven't tried.

**Comment by hoagN1** [comment]
thank you so muchhhhh

**Comment by bitcookies** [comment]
> thank you so muchhhhh

ok 😜
