### ISSUE TITLE
InternalError: The length of register data is not correct.

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [bitcookies/winrar-keygen#6]
The error `InternalError: The length of register data is not correct.` is sometimes returned while generating a key.

After some testing, I discovered that the length checks that should prevent that error in the first place, are incorrect.

first:

https://github.com/bitcookies/winrar-keygen/blob/4d7ecf7e217eb0bd0353b954eec3774442994701/WinRarKeygen.hpp#L196

Pad with zeros, and `<=` should be `==` : 

```C++
if (LicenseTypeSignatureR.length() < 60) {
    LicenseTypeSignatureR.insert(LicenseTypeSignatureR.begin(), 60 - LicenseTypeSignatureR.size(), '0');
}
if (LicenseTypeSignatureS.length() < 60) {
    LicenseTypeSignatureS.insert(LicenseTypeSignatureS.begin(), 60 - LicenseTypeSignatureS.size(), '0');
}
if (LicenseTypeSignatureR.length() == 60 && LicenseTypeSignatureS.length() == 60) { 
```

second:

https://github.com/bitcookies/winrar-keygen/blob/4d7ecf7e217eb0bd0353b954eec3774442994701/WinRarKeygen.hpp#L207

same as above, **and** `||` should be `&&`:

```C++
if (UserNameSignatureR.length() < 60) {
    UserNameSignatureR.insert(UserNameSignatureR.begin(), 60 - UserNameSignatureR.size(), '0');
}
if (UserNameSignatureS.length() < 60) {
    UserNameSignatureS.insert(UserNameSignatureS.begin(), 60 - UserNameSignatureS.size(), '0');
}
if (UserNameSignatureR.length() == 60 && UserNameSignatureS.length() == 60) { 
```

These changes should get rid of that error.

**Comment by bitcookies** [comment]
Cool 😎. Many thanks, fix it later.

**Comment by bitcookies** [comment]
Done 😎
