### ISSUE TITLE
Format string causes undefined behavior

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [bitcookies/winrar-keygen#7]
The format string "60%**0**60**s**%**0**60**s**" at:
https://github.com/bitcookies/winrar-keygen/blob/fbc4fb257626bba65b63bc0ebf4fd141f6c249dc/WinRarKeygen.hpp#L214
and 
https://github.com/bitcookies/winrar-keygen/blob/fbc4fb257626bba65b63bc0ebf4fd141f6c249dc/WinRarKeygen.hpp#L242
is not valid, the "0" flag cannot be combined with the "s" specifier.

The string should be replaced with `"60%s%s"` like this:

https://github.com/bitcookies/winrar-keygen/blob/fbc4fb257626bba65b63bc0ebf4fd141f6c249dc/WinRarKeygen.hpp#L214
should be replaced by:
```C++
RegInfo.Items[1] = HelperStringFormat("60%s%s", LicenseTypeSignatureS.c_str(), LicenseTypeSignatureR.c_str());
```
and
https://github.com/bitcookies/winrar-keygen/blob/fbc4fb257626bba65b63bc0ebf4fd141f6c249dc/WinRarKeygen.hpp#L242
should be replaced by:
```C++
RegInfo.Items[2] = HelperStringFormat("60%s%s", UserNameSignatureS.c_str(), UserNameSignatureR.c_str()); 
```
The changes introduced in #6 already ensure the strings to be formatted are exactly 60 chars.

**Comment by bitcookies** [comment]
Thanks, I'll take a look. 👍

**Comment by bitcookies** [comment]
I found a bug, the keys generated by **Github Actions** are all invalid. 😥

I can't find the reason, is it because of the cloud windows coding problem?

If you have a spare time, can you help to check it out?

**Comment by bitcookies** [comment]
I find that:

The key generated in this way is valid:
```
winrar-keygen.exe text1 text2"
```
but the key generated in this way is invalid:
```
winrar-keygen.exe text1 text2 > rarreg.key
```

**Comment by bitcookies** [comment]
Ohh. It's because powershell is outputting in **UTF16-LE** format by default, which is causing the error. I fixed.

Format string issues was also fixed using your suggestion. Thanks again! 😄
